version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.20
    steps:
      - checkout
      - restore_cache:
          key: module-cache-{{ checksum "go.mod" }}
      - run:
          name: Check dependencies
          command: make deps
      - run:
          name: Test with coverage
          command: make test-cover
      - save_cache:
          key: module-cache-{{ checksum "go.mod" }}
          paths:
            - $HOME/go/pkg/mod/cache/download/
